name = "curvature_replication"
uuid = "e93cd083-fa86-4401-85c6-2bd0ceb7a2cd"
authors = ["Joshua Niemelä <josh@jniemela.dk>"]
version = "0.1.0"

[deps]
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
