program: train.py
project: TreeBottleneckReproduction
name: sweepdemo
method: random
metric:
  goal: maximize
  name: train_accuracy
parameters:
  model_type:
    values: ["GAT", "GCN", "GGNN", "GIN"]
  tree_depth:
    values: [3, 4, 5]
  num_trees:
    values: [40000]
  epochs:
    values: [1000]
  lr:
    values: [0.01]
  batch_size:
    values: [2048]
  hidden_dim:
    values: [32]
  early_stop_patience:
    values: [20]
  early_stop_grace_period:
    values: [50]
  stopping_threshold:
    values: [0.0001]
  scheduler_factor:
    values: [0.75]
  scheduler_patience:
    values: [5]
  fully_adjacent_last_layer:
    values: [false]
