program: train_with_wandb.py
project: TreeBottleneckReproduction
name: sweepdemo
method: random
metric:
  goal: maximize
  name: train_accuracy
parameters:
  model_type:
    values: ["GCN"]
  tree_depth:
    values: [2, 3, 4, 5]
  num_trees:
    values: [40000, 80000]
  max_epochs:
    values: [50000]
  lr:
    values: [0.01]
  batch_size:
    values: [2048, 3072]
  hidden_dim:
    values: [32]
  early_stop_patience:
    values: [25]
  early_stop_grace_period:
    values: [100]
  stopping_threshold:
    values: [0.0001]
  scheduler_factor:
    values: [0.9]
  scheduler_patience:
    values: [20]
  fully_adjacent_last_layer:
    values: [false, true]
  mlp_aggregation:
    values: [true, false]
