program: train_with_wandb.py
project: TreeBottleneckReproduction
name: sweepdemo
method: random
metric:
  goal: maximize
  name: train_accuracy
parameters:
  model_type:
    values: ["GCN"]
  tree_depth:
    values: [4, 5]
  num_trees:
    values: [20000]
  max_epochs:
    values: [50000]
  lr:
    values: [0.01, 0.001]
  batch_size:
    values: [2048]
  hidden_dim:
    values: [32]
  early_stop_patience:
    values: [20]
  early_stop_grace_period:
    values: [20]
  stopping_threshold:
    values: [0.0001]
  scheduler_factor:
    values: [0.5]
  scheduler_patience:
    values: [10]
  fully_adjacent_last_layer:
    values: [false]
